### ISSUE TITLE
Collection with user_created can not be created. 

### ISSUE THREAD

**Issue by Cruze** [directus/directus#10876]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

```json
{
  "errors": [
    {
      "message": "alter table XYZ add constraint XYZ_user_created_foreign foreign key (user_created) references directus_users (id) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'invoices_user_created_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Create a new collection with user_created and press save

### Errors Shown

```json
{
  "errors": [
    {
      "message": "alter table XYZ add constraint XYZ_user_created_foreign foreign key (user_created) references directus_users (id) - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'invoices_user_created_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.4.1

### What version of Node.js are you using?

14.17.5

### What database are you using?

MySQL 8.0.27

### What browser are you using?

Edge latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

cloud

**Comment by rijkvanzanten** [comment]
What charset/collation are you using on the database, and did you tell Directus to use that same charset/collation through the `DB_CHARSET` environment variable?

**Comment by Cruze** [comment]
Hi, i use utf8mb4 in the database and in the .env file. This works fine, till now. 
I rechecked it. It works if i do not setup "user_created".

**Comment by rijkvanzanten** [comment]
@Cruze How / when are you creating this `user_created` field? When creating a new collection?

**Comment by Cruze** [comment]
When i create a new collection and select also sort, user_created....

**Comment by Cruze** [comment]
I have set up a completely new directus project and created my first collection. Unfortunately with the same error

**Comment by rijkvanzanten** [comment]
@Cruze Where / how are you deploying Directus exactly? 🤔

**Comment by Cruze** [comment]
Hetzner Cloud with Ubuntu 20.04 with Virtualmin.
MySQL version 8.0.27-0ubuntu0.20.04.1
Installation is done by CLI
npm init directus-project my-project
npx directus start

**Comment by Cruze** [comment]
I have the same problem when I create a field to directus_files.
In a collection "invoice_files" I create a field called "file_id". After saving I get this error. 

{
  "errors": [
    {
      "message": "alter table `invoice_files` add constraint `invoice_files_file_id_foreign` foreign key (`file_id`) references `directus_files` (`id`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'file_id' and referenced column 'id' in foreign key constraint 'invoice_files_file_id_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

**Comment by rijkvanzanten** [comment]
Have you used DB_CHARSET="utf8mb4" since the start, and during the installation of Directus? If you inspect the database, do all tables/columns use the same charset/collation?

**Comment by Alv-sys** [comment]
I am experiencing the same issue, using my local environment, W11 with MySQL 8.0.27, using Directus 9.4.3

It could be a bit different so I am going to show some evidence, so if is necessary I can create a different thread, but in essence is the same, and also never happened to me with the RC versions.

I checked manually the DB charset/collation and I set the .env with the same, but I got same error. In my experience seems to be a bit random, but usually is generated as @Cruze mentioned, by selecting the system fields.

![image](https://user-images.githubusercontent.com/47535920/149060725-0b3ef9e9-2ad3-471c-adb8-8ef998f8aa1e.png)
![image](https://user-images.githubusercontent.com/47535920/149060748-8c5a576d-b42d-43bc-848d-b5be4f7855d9.png)

And I get the error 
![image](https://user-images.githubusercontent.com/47535920/149060791-ecbaf1b4-5dcf-4bba-bf05-40a8c5b07d3c.png)

If I change page and after return to Collections, I can see the field created as Database only and a folder:
![image](https://user-images.githubusercontent.com/47535920/149061038-9e0c138f-c118-4c6a-8e2e-74477b824328.png)
![image](https://user-images.githubusercontent.com/47535920/149060970-7a477026-a925-46ab-a802-1cbcf1cee615.png)

After get the error, usually the following collections created doesn't have the issue, for example this one works:
![image](https://user-images.githubusercontent.com/47535920/149061406-5e5b3af0-17ce-464b-a96d-c6cae5c9a5ca.png)

but right after that, creating this, I received same behaviour:
![image](https://user-images.githubusercontent.com/47535920/149061437-068ebe54-ccce-4f73-8337-bc58524148d9.png)
![image](https://user-images.githubusercontent.com/47535920/149061476-f24c3197-11f1-44aa-b45b-110e8ccf9224.png)

It is really weird, but it happens consistently

PD:  Just as a extra information, in case it would help to find the cause, it tends to happen more often when I use keywords as "Pages", "Blog", "Random".

**Comment by Cruze** [comment]
Hi Rijk, i checked again and all tables have are utf8mb4_general_ci. I also installed a complete new version without any custom collections with the same result.

**Comment by Oreilles** [comment]
> Hi Rijk, i checked again and all tables have are utf8mb4_general_ci. I also installed a complete new version without any custom collections with the same result.

This is still being discussed, but you should try **removing** the `DB_CHARSET` variable from your environment.

Checking that the tables are `utf8mb4_general_ci` is not enough: you need to check that the *columns* inside those table are `utf8mb4_general_ci` too.
Then, you want to check, in a database admin tool if your database default collation also is `utf8mb4_general_ci`. You can do that with `SELECT @@collation_database;`

If that is the case, then everything should work again. If some of your columns/tables aren't matching the database default collation, you should alter the collation for every column in those tables, and for the table too, e.g: `ALTER TABLE foo MODIFY bar CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci` etc.

**Comment by Cruze** [comment]
Hi, i checked tables, columns
Character: utf8mb4
Collation: utf8mb4_general_ci
I also created an export and checked the file. the same result. I can not see differences.

**Comment by Oreilles** [comment]
Did you remove `DB_CHARSET` from your env ?
Can you confirm that `SELECT @@collation_database` also returns `utf8mb4_general_ci` ?
Can you confirm that both the table `directus_users` and the table `XYZ` you tried to create with system fields and all of their column also are `utf8mb4_general_ci` ?

**Comment by Oreilles** [comment]
If all of this is true, things should be working as expected. Are you facing the issue even after setting up a new project on a clean database ?

**Comment by Cruze** [comment]
SELECT @@collation_database

**Comment by Cruze** [comment]
I have checked the settings and they are correct. The error still appears, even with a completely new project

**Comment by Cruze** [comment]
I tried another test. New installation with UTF8. That's working like expected. I tried another installation with utf8mb4 and DB_CHARSET='UTF8MB4'. This solution is not working. I deleted DB_CHARSET='UTF8MB4' and start directus again. In this case it's working.

**Comment by Cruze** [comment]
I removed DB_CHARSET again, recreated database and now it works. Thanks!

**Comment by rijkvanzanten** [comment]
@Cruze Do you still have the original broken database? If at all possible, could you send a database dump of the broken one? I'm really curious what else might be causing this issue 🤔

**Comment by Oreilles** [comment]
@rijkvanzanten I was a misconception of me that the default collation use for the connection by `node-mysql` was the database default one: `node-mysql` use `utf8_general_ci` regardless. I'm about to submit a draft PR that should prevent most of this issues.

**Comment by Cruze** [comment]
I will check for a dump without data.
