### ISSUE TITLE
textinput readonly flag does not work

### ISSUE THREAD

**Issue by timonmat** [directus/directus#1280]
hey, the readonly flag in textinput field type does not seem to have any effect. The field remains editable, and changes are saved to db.

I have a field where i trigger a UUID() in mysql on insert. I'd like it to be visible, but not editable. can't seem to make that happen.
## Version Info
- Directus version and branch: 6.3.4
- PHP version: 7
- MySQL version: Mariadb 10.1.18
- Web server: (Ex. Apache, nginx or IIS?) apache
- OS name and version: docker / debian jessie
## Expected Behavior

readonly to gray out the input field, but still show the value of field.
## Actual Behavior

readonly flag has no effect. field is editable.
## Steps to Reproduce
1. create table
2. create textinput field and select readonly flag in options. save.
3. add value to field. it's saved.

**Comment by WellingGuzman** [comment]
Hi @timonmat, I'm working on it.

**Comment by WellingGuzman** [comment]
Hey @timonmat this commit https://github.com/directus/directus/commit/8b726d7cfd8ca2372e493abd43ddabe7c4e293b0 should fix the issue.

Let me know.

**Comment by WellingGuzman** [comment]
Hey @timonmat Closing it. let me know if I didn't work and I will reopen it and work on it.

Thanks,

**Comment by timonmat** [comment]
@WellingGuzman 
I can still reproduce on 6.3.5. 

Text field with 'read only' flag enabled looks normal, i.e. not dimmed, and is saved when changed.

**Comment by WellingGuzman** [comment]
Hey @timonmat when you inspect the input element in devtools does it has the `readonly` attribute?

**Comment by timonmat** [comment]
@WellingGuzman No, it doesn't.

![image](https://cloud.githubusercontent.com/assets/15153521/20406170/e4540c02-ad14-11e6-9b23-a5ab4b0d6f98.png)

**Comment by timonmat** [comment]
...and now it works as expected. grade A voodoo stuff. I honestly didn't change a thing, and now the same field works as expected, and the readonly flag is in the element. It couldn't have been coming from cache, because I loaded that page first with devtools and cache disabled. 

I think you can keep this closed. I'll find a better sequence if it pops up again.

**Comment by benhaynes** [comment]
Thanks for trying to replicate @timonmat – much appreciated! Not a fan of the intermittent issues... 😕  ... but either way, glad it's working for you.
