### ISSUE TITLE
Error on uploading new user image

### ISSUE THREAD

**Issue by airbenich** [directus/directus#1303]
## Version Info
  - Directus version and branch: 6.3.4 master
  - PHP version: 5.5
  - MySQL version: n/a
  - Web server: Apache
  - OS name and version: OSX 10.11

## Expected Behavior
New User-Image should be uploaded when selecting a new one and pressing save

## Actual Behavior
After selecting and pressing save an error appears:
Server Error
Invalid argument supplied for foreach()

## Steps to Reproduce
 1. Click on the user-image in the sidebar left
 2. Select a new image to upload / remove the old image if there is one
 3. Click Sache item
 4. Take a look at the error message

**Comment by WellingGuzman** [comment]
Hey @airbenich, Thanks for reporting this issue.

if there's any log files in `api/logs`, please show me what's inside.

I tried on master branch without any luck.

**Comment by airbenich** [comment]
Here is the log-file. I deleted it before i took the steps to reproduce:

```
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\TableGateway\AclAwareTableGateway::makeTableGatewayFromTableName() should be compatible with Directus\Db\TableGateway\BaseTableGateway::makeTableGatewayFromTableName($table, $adapter)' in /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:0
Stack trace:
#0 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/vhosts...', 0, Array)
#1 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#4 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(9): spl_autoload_call('Directus\Db\Tab...')
#5 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): include('/var/www/vhosts...')
#6 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#8 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(328): spl_autoload_call('Directus\Db\Tab...')
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/vhosts/domain/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\RowGateway\AclAwareRowGateway::makeRowGatewayFromTableName() should be compatible with Directus\Db\RowGateway\BaseRowGateway::makeRowGatewayFromTableName($table, $adapter, $primaryKeyColumn = 'id')' in /var/www/vhosts/domain/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php:18
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php(18): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/vhosts...', 18, Array)
#1 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): include('/var/www/vhosts...')
#2 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Row...')
#4 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(52): spl_autoload_call('Directus\Db\Row...')
#5 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(17): Directus\Db\TableGateway\AclAwareTableGateway->__construct(Object(Directus\Acl\Acl), 'directus_tables', Object(Directus\Db\Connection))
#6 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(328): Directus\Db\TableGateway\DirectusTablesTableGateway->__construct(Object(Directus\Acl\Acl), Object(Directus\Db\Connection))
#7 [internal function]: Directus\Bootstrap::acl(NULL)
#8 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#9 /var/www/vhosts/domain/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#10 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'array_filter() expects parameter 1 to be array, boolean given' in /var/www/vhosts/domain/directus/api/core/functions.php:726
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_filter() ...', '/var/www/vhosts...', 726, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(726): array_filter(false, Object(Closure))
#2 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#4 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#5 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /var/www/vhosts/domain/directus/api/core/functions.php:727
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_merge(): ...', '/var/www/vhosts...', 727, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(727): array_merge(Array, NULL)
#2 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#4 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#5 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/core/functions.php:730
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/functions.php(730): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/var/www/vhosts...', 730, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#2 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#3 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#4 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/api.php:281
Stack trace:
#0 /var/www/vhosts/domain/directus/api/api.php(281): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/var/www/vhosts...', 281, Array)
#1 {main}
ERROR - 2016-11-15T13:05:05-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php:510
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(510): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/var/www/vhosts...', 510, Array)
#1 [internal function]: Directus\Bootstrap::embedManager(NULL)
#2 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(603): Directus\Bootstrap::get('embedManager')
#4 [internal function]: Directus\Bootstrap::Directus\{closure}(Object(Zend\Db\ResultSet\ResultSet), Array)
#5 /var/www/vhosts/domain/directus/api/core/Directus/Hook/Emitter.php(236): call_user_func_array(Object(Closure), Array)
#6 /var/www/vhosts/domain/directus/api/core/Directus/Hook/Emitter.php(135): Directus\Hook\Emitter->executeListeners(Array, Array, 1)
#7 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(577): Directus\Hook\Emitter->apply('table.select', Array)
#8 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(557): Directus\Db\TableGateway\BaseTableGateway->applyHook('table.select', Array)
#9 /var/www/vhosts/domain/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#10 /var/www/vhosts/domain/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#11 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(180): Zend\Db\TableGateway\AbstractTableGateway->select(Object(Closure))
#12 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(281): Directus\Db\TableGateway\BaseTableGateway->fetchAll(Object(Closure))
#13 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(374): Directus\Db\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array, 'directus_files')
#14 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(79): Directus\Db\TableGateway\RelationalTableGateway->addOrUpdateManyToOneRelationships(Array, Array, Array, false)
#15 /var/www/vhosts/domain/directus/api/api.php(815): Directus\Db\TableGateway\RelationalTableGateway->manageRecordUpdate('directus_users', Array, 1)
#16 [internal function]: {closure}('directus_users', '2')
#17 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#18 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#19 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#20 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#21 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Slim.php(1254): Slim\Middleware\MethodOverride->call()
#22 /var/www/vhosts/domain/directus/api/api.php(1696): Slim\Slim->run()
#23 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\TableGateway\AclAwareTableGateway::makeTableGatewayFromTableName() should be compatible with Directus\Db\TableGateway\BaseTableGateway::makeTableGatewayFromTableName($table, $adapter)' in /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:0
Stack trace:
#0 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/vhosts...', 0, Array)
#1 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#4 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(9): spl_autoload_call('Directus\Db\Tab...')
#5 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): include('/var/www/vhosts...')
#6 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#8 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(328): spl_autoload_call('Directus\Db\Tab...')
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/vhosts/domain/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\RowGateway\AclAwareRowGateway::makeRowGatewayFromTableName() should be compatible with Directus\Db\RowGateway\BaseRowGateway::makeRowGatewayFromTableName($table, $adapter, $primaryKeyColumn = 'id')' in /var/www/vhosts/domain/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php:18
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/Directus/Db/RowGateway/AclAwareRowGateway.php(18): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/vhosts...', 18, Array)
#1 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(412): include('/var/www/vhosts...')
#2 /var/www/vhosts/domain/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/vhosts...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Row...')
#4 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(52): spl_autoload_call('Directus\Db\Row...')
#5 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(17): Directus\Db\TableGateway\AclAwareTableGateway->__construct(Object(Directus\Acl\Acl), 'directus_tables', Object(Directus\Db\Connection))
#6 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(328): Directus\Db\TableGateway\DirectusTablesTableGateway->__construct(Object(Directus\Acl\Acl), Object(Directus\Db\Connection))
#7 [internal function]: Directus\Bootstrap::acl(NULL)
#8 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#9 /var/www/vhosts/domain/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#10 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'array_filter() expects parameter 1 to be array, boolean given' in /var/www/vhosts/domain/directus/api/core/functions.php:726
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_filter() ...', '/var/www/vhosts...', 726, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(726): array_filter(false, Object(Closure))
#2 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#4 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#5 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /var/www/vhosts/domain/directus/api/core/functions.php:727
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_merge(): ...', '/var/www/vhosts...', 727, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(727): array_merge(Array, NULL)
#2 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#4 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#5 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/core/functions.php:730
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/functions.php(730): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/var/www/vhosts...', 730, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(769): find_files('/var/www/vhosts...', 0, '*.php', true)
#2 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(81): find_php_files('/var/www/vhosts...', true)
#3 /var/www/vhosts/domain/directus/api/api.php(280): Directus\Bootstrap::getCustomEndpoints()
#4 {main}
ERROR - 2016-11-15T13:05:10-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/api.php:281
Stack trace:
#0 /var/www/vhosts/domain/directus/api/api.php(281): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/var/www/vhosts...', 281, Array)
#1 {main}
```

**Comment by mkly** [comment]
https://github.com/directus/directus/commit/21b00e99be734c5274f6f5b2413cb945cab80496

Looks like this might have been addressed somewhat? Maybe you need to to update to the latest master?

**Comment by WellingGuzman** [comment]
Yes that's the problem, I have been stretching the days to release the new version with this fix.

Can you please use the master branch while I work on the release?

**Comment by airbenich** [comment]
Okay, i've updated to the latest master. Error is still present.
Can you inform on this thread when the fix is released?
Thank you for your work guys! :)

**Comment by WellingGuzman** [comment]
Hey @airbenich, I'm far from a computer, please use development branch it should be fixed there.

I will inform you as soon as I fix it today and release the new version.

Thank you for using Directus :)

**Comment by WellingGuzman** [comment]
@airbenich master branch is updated and `6.3.5` was released. it should be good to go now. Otherwise let us know.

**Comment by airbenich** [comment]
Still the same problem.
I replaced all files on the server with the new master branch. "6.3.5" is also mentioned in the bottom left corner on login screen. Is there a way to check if my installation works correct? I installed it on sunday using master branch 6.3.4.

**Comment by WellingGuzman** [comment]
can you share you logs (`api/logs`) again? I want to see if there's the same issue you are having or another one.

**Comment by airbenich** [comment]
shure!

```
ERROR - 2016-11-16T12:55:15-05:00 - exception 'ErrorException' with message 'array_filter() expects parameter 1 to be array, boolean given' in /var/www/vhosts/domain/directus/api/core/functions.php:726
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_filter() ...', '/var/www/vhosts...', 726, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(726): array_filter(false, Object(Closure))
#2 /var/www/vhosts/domain/directus/api/core/functions.php(754): find_files('/var/www/vhosts...', 0, '*.js', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(433): find_js_files('/var/www/vhosts...', true)
#4 [internal function]: Directus\Bootstrap::uis(NULL)
#5 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#6 /var/www/vhosts/domain/directus/index.php(344): Directus\Bootstrap::get('uis')
#7 /var/www/vhosts/domain/directus/index.php(454): getUI()
#8 {main}
ERROR - 2016-11-16T12:55:15-05:00 - exception 'ErrorException' with message 'array_merge(): Argument #2 is not an array' in /var/www/vhosts/domain/directus/api/core/functions.php:727
Stack trace:
#0 [internal function]: Directus\Exception\ExceptionHandler->handleError(2, 'array_merge(): ...', '/var/www/vhosts...', 727, Array)
#1 /var/www/vhosts/domain/directus/api/core/functions.php(727): array_merge(Array, NULL)
#2 /var/www/vhosts/domain/directus/api/core/functions.php(754): find_files('/var/www/vhosts...', 0, '*.js', true)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(433): find_js_files('/var/www/vhosts...', true)
#4 [internal function]: Directus\Bootstrap::uis(NULL)
#5 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#6 /var/www/vhosts/domain/directus/index.php(344): Directus\Bootstrap::get('uis')
#7 /var/www/vhosts/domain/directus/index.php(454): getUI()
#8 {main}
ERROR - 2016-11-16T12:55:15-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php:434
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(434): Directus\Exception\ExceptionHandler->handleError(2, 'Invalid argumen...', '/var/www/vhosts...', 434, Array)
#1 [internal function]: Directus\Bootstrap::uis(NULL)
#2 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#3 /var/www/vhosts/domain/directus/index.php(344): Directus\Bootstrap::get('uis')
#4 /var/www/vhosts/domain/directus/index.php(454): getUI()
#5 {main}
ERROR - 2016-11-16T12:55:26-05:00 - exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php:513
Stack trace:
#0 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(513): Slim\Slim::handleErrors(2, 'Invalid argumen...', '/var/www/vhosts...', 513, Array)
#1 [internal function]: Directus\Bootstrap::embedManager(NULL)
#2 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#3 /var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php(606): Directus\Bootstrap::get('embedManager')
#4 [internal function]: Directus\Bootstrap::Directus\{closure}(Object(Zend\Db\ResultSet\ResultSet), Array)
#5 /var/www/vhosts/domain/directus/api/core/Directus/Hook/Emitter.php(236): call_user_func_array(Object(Closure), Array)
#6 /var/www/vhosts/domain/directus/api/core/Directus/Hook/Emitter.php(135): Directus\Hook\Emitter->executeListeners(Array, Array, 1)
#7 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(589): Directus\Hook\Emitter->apply('table.select', Array)
#8 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(569): Directus\Db\TableGateway\BaseTableGateway->applyHook('table.select', Array)
#9 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#10 /var/www/vhosts/domain/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#11 /var/www/vhosts/domain/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#12 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(210): Zend\Db\TableGateway\AbstractTableGateway->select(Object(Closure))
#13 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(182): Directus\Db\TableGateway\BaseTableGateway->findOneBy('id', '36')
#14 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(224): Directus\Db\TableGateway\BaseTableGateway->find('36')
#15 /var/www/vhosts/domain/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(258): Directus\Db\TableGateway\AclAwareTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#16 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(257): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#17 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(384): Directus\Db\TableGateway\BaseTableGateway->addOrUpdateRecordByArray(Array, 'directus_files')
#18 /var/www/vhosts/domain/directus/api/core/Directus/Db/TableGateway/RelationalTableGateway.php(80): Directus\Db\TableGateway\RelationalTableGateway->addOrUpdateManyToOneRelationships(Array, Array, Array, false)
#19 /var/www/vhosts/domain/directus/api/api.php(825): Directus\Db\TableGateway\RelationalTableGateway->manageRecordUpdate('directus_users', Array, 1)
#20 [internal function]: {closure}('directus_users', '2')
#21 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#22 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#23 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#24 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#25 /var/www/vhosts/domain/directus/api/core/Directus/Slim/CorsMiddleware.php(22): Slim\Middleware\MethodOverride->call()
#26 /var/www/vhosts/domain/directus/vendor/slim/slim/Slim/Slim.php(1254): Directus\Slim\CorsMiddleware->call()
#27 /var/www/vhosts/domain/directus/api/api.php(1705): Slim\Slim->run()
#28 {main}
```

**Comment by airbenich** [comment]
And: 
![bildschirmfoto 2016-11-16 um 18 57 40](https://cloud.githubusercontent.com/assets/13045725/20359083/97a08cd2-ac2e-11e6-8012-ddfbf83056b0.png)

**Comment by WellingGuzman** [comment]
Hey @airbenich, looking at your logs I want to see what's on line `513` in this file `/var/www/vhosts/domain/directus/api/core/Directus/Bootstrap.php:513` I'm wondering because I do not have a foreach in there, and I want to make sure you have the latest code.

**Comment by airbenich** [comment]
![bildschirmfoto 2016-11-16 um 19 31 20](https://cloud.githubusercontent.com/assets/13045725/20360242/455a6db2-ac33-11e6-8662-0e3d64667a44.png)

**Comment by airbenich** [comment]
Mhh yep in my code there is a foreach. -> But in the master branch of directs/directus also:
https://github.com/directus/directus/blob/master/api/core/Directus/Bootstrap.php#L513

**Comment by WellingGuzman** [comment]
Thanks, I just confirmed I wasn't looking at the master branch, I apologies.

**Comment by WellingGuzman** [comment]
Hey @airbenich can you join our Slack (http://slack.getdirectus.com) so I can help you over there more personally.

I want to see what value is `$path` storing.
