### ISSUE TITLE
"Choose existing" (M2M) throws an SQL error when the related table has a gallery

### ISSUE THREAD

**Issue by peremp** [directus/directus#1603]
## Version Info
  - Directus version and branch: 6.4 latest

## Preparation
 1. Install Directus 6.4
 2. Import the SQL to the DB to create all the tables/relations needed to reproduce the bug: [Download SQL](https://drive.google.com/file/d/0B0sF62qJHeE5dS03QVlBcXdRT2s/view)

## Steps to Reproduce
 1.  Create a "Solution" with a Title & Image.
 2.  Create a "Problem" with a title, and use the "Choose existing" button to add the solution created on step 1.

## Expected Behavior
Problem is created. The solution is linked.

## Actual Behavior
This query failed: UPDATE `directus_files` SET `id` = '3', `active` = '1', `name` = '00000000003.jpg', `title` = 'avatar samuel edwards 1497942559', `location` = '', `caption` = '', `type` = 'image/jpeg', `charset` = 'binary', `tags` = '', `width` = '128', `height` = '128', `size` = '4438', `embed_id` = NULL, `user` = '1', `storage_adapter` = 'local', `url` = '/forks/directus/storage/uploads/00000000003.jpg', `thumbnail_url` = '/forks/directus/storage/uploads/thumbs/3.jpg', `old_thumbnail_url` = '/forks/directus/storage/uploads/thumbs/00000000003-jpg-160-160-true.jpg', `html` = NULL WHERE `id` = '3'

**Comment by WellingGuzman** [comment]
Hey @peremp pull the latest commit and see if it was solve, I was working with O2M earlier today, so probably this was fixed along the way.

**Comment by peremp** [comment]
This still happens.
Note that this only happens on creation. Later on edition you can add related solutions with images and works fine.

**Comment by WellingGuzman** [comment]
can you drag and drop the file here or send me a PM on slack?

**Comment by peremp** [comment]
Ok, lets continue on slack :)

**Comment by peremp** [comment]
Do you have an ETA for this? this is a big issue for our editors :-(

I can try to fix it, but some guidance would be nice so I do not waste too much time just looking for the root of the problem.

**Comment by WellingGuzman** [comment]
Hey @peremp, this issue was fixed by https://github.com/directus/directus/commit/567eadd77e4a64fd00a5db972caa9477ca4ed42f

Please confirm.

**Comment by peremp** [comment]
It works :)

**Comment by WellingGuzman** [comment]
Awesome! I will close it, if happens in a again or a similar issue I will reopen, hopefully this will solve it, but we never know.
