### ISSUE TITLE
Unable to create decimal field

### ISSUE THREAD

**Issue by piupiupiu** [directus/directus#1709]
## Version Info
  - Directus version and branch: master branch, latest commit #da6d751 
  - PHP version: 7.0 fpm
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) nginx
  - OS name and version: ubuntu 16.04

## Expected Behavior
A new column is created.

## Actual Behavior
Column is not created. An sql error is showing.

## Steps to Reproduce
 1. Add new field 
 2. Select numeric data type.
 3. Select decimal. Leave the default length.
 4. Press save. You'll see the error (see attached)

## Logs or Screenshots
![image](https://user-images.githubusercontent.com/4255839/28563190-db201c1a-712d-11e7-9b51-ede0cb7e7a0f.png)
![image](https://user-images.githubusercontent.com/4255839/28563272-1984c424-712e-11e7-8aa3-081accb7a7ff.png)

**Comment by WellingGuzman** [comment]
Thanks for reporting this @piupiupiu. This has been fixed by https://github.com/directus/directus/commit/e65b4ef028fbf761386826f90a6c240e596aaff8

Please confirm.

**Comment by piupiupiu** [comment]
@WellingGuzman, I've made the checkout, but the issue still persists. Conditions and the behavior is exactly the same.

**Comment by WellingGuzman** [comment]
can you explain what you did @piupiupiu as this potentially may have fixed the issue? can you share the logs on api/logs?

**Comment by benhaynes** [comment]
Hey @piupiupiu – we've been testing this one and are able to successfully create the DECIMAL column every time. Perhaps it's something to do with your configuration or server/sql setup? Any detailed logs or other info would be greatly appreciated.

In the meantime, we're going to close this one since it is working for multiple people following your exact steps. Please re-open if you submit more details/info. Thanks!

**Comment by magbeat** [comment]
Hey @benhaynes. The column is indeed created successfully in the database. But the UI seems not handle it correctly. I cannot store a decimal number:  

![image](https://user-images.githubusercontent.com/1089410/29753412-36c0ffd2-8b71-11e7-9710-41fa4ec0570a.png)

![image](https://user-images.githubusercontent.com/1089410/29753415-3f92bcf4-8b71-11e7-8046-5e52f596ed61.png)

And in the overview the column is represented as int instead of a decimal:

![image](https://user-images.githubusercontent.com/1089410/29753422-609ae8d6-8b71-11e7-9dd1-dc7e506b4ecc.png)

The definition is:

![image](https://user-images.githubusercontent.com/1089410/29753426-786e2e3c-8b71-11e7-897e-43d36616f2ec.png)

**Comment by WellingGuzman** [comment]
Hey @magbeat, I just bumped into that issue last night.

---

@rijkvanzanten the reason is that the input value is empty when the browser `checkValidity` function try to valides its value.

**Comment by rijkvanzanten** [comment]
Interesting, I'll check it out!
