### ISSUE TITLE
The Settings menu does not show the correct Directus version

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#17115]
### Describe the Bug

The Settings menu does not show the correct Directus version.
Project updated to `v9.22.4` showing `v9.22.3`:

<img width="291" alt="Screenshot_2023-01-11_at_6 59 58_PM" src="https://user-images.githubusercontent.com/1007051/212086025-b4856583-143f-4fd1-9e7d-66583eb65f0a.png">

We have seen it after update project from `v9.22.1` to `v9.22.4`.
But also creating now a new project with: `npm init directus-project my-project`

### To Reproduce

- Create a new project with: `npm init directus-project my-project`
- Run `npx directus start`
- See the Settings menu

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/commit/5e27e8c928540207aa5decff4f1821c51f4a765d

**Comment by abdonrd** [comment]
@rijkvanzanten should we expect a new release soon?
It seems that v9.22.4 still does not exist:
https://www.npmjs.com/package/@directus/app?activeTab=versions
https://www.npmjs.com/package/@directus/shared?activeTab=versions

**Comment by rijkvanzanten** [comment]
@abdonrd It _is_ the build with the latest changes though, so that part should be OK. I'll push out another patch shortly to finally unstick this

**Comment by abdonrd** [comment]
> @abdonrd It _is_ the build with the latest changes though, so that part should be OK. I'll push out another patch shortly to finally unstick this

@rijkvanzanten finally there will be no patch soon? Thanks!

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten looks like it is still an issue with the latest version:
> 
> * [After the update, the description of the version does not agree #17653](https://github.com/directus/directus/issues/17653)
> 
> npm registry:
> 
> * https://www.npmjs.com/package/directus?activeTab=versions
> * https://www.npmjs.com/package/@directus/app?activeTab=versions
> * https://www.npmjs.com/package/@directus/shared?activeTab=versions

Nah the problem was fixed, but it didn't go out to npm correctly. Apparently something changed in the way authentication works for publishes since the last time we published, as there's an error in the release flow now: https://github.com/directus/directus/actions/runs/4295889524/jobs/7486979867#step:5:46

**Comment by abdonrd** [comment]
> Nah the problem was fixed, but it didn't go out to npm correctly. Apparently something changed in the way authentication works for publishes since the last time we published, as there's an error in the release flow now: https://github.com/directus/directus/actions/runs/4295889524/jobs/7486979867#step:5:46

Oooh, okey! Thanks for the info!

**Comment by rijkvanzanten** [comment]
@abdonrd All good now 👍🏻
