### ISSUE TITLE
WYSIWYG Full editor size issue

### ISSUE THREAD

**Issue by MarcinKuder** [directus/directus#1759]
## Version Info
  - Directus version and branch: (Or commit hash)
directus-build-6.4.2.20170823180744.tar.gz
  - OS name and version: 
Windows 10, Chrome, Firefox

## Actual Behavior
The WYSIWYG Full editor has only 300px width and 150px height (which is not resizeable, regardless of the max height settings)
Simple WYSIWG on the other hand, fills the whole width and looks fine.

Additional question - is it possible to add a Directus uploaded file as an image in WYSIWYG full? I mean a file chooser. I know that it can be done by providing a relative url to the image.

## Steps to Reproduce
 1.  Add WYSIWYG Full with default settings

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/1597894/29640457-5bbe9494-885f-11e7-822b-b0ce651b4144.png)

**Comment by rijkvanzanten** [comment]
Hmm, this seems to be a Windows specific issue, as I have not been able to replicate this in Chrome/Firefox on MacOS Sierra.

**Comment by rijkvanzanten** [comment]
@MarcinKuder It isn't possible to select from your uploaded files to include them _yet_. It's on the roadmap however.

**Comment by prudolph81** [comment]
Same issue here, I added
`div.mce-edit-area iframe {
        width: 100%;
    }`
to app/core/interfaces/wysiwyg_full/input.html to solve this.

**Comment by rijkvanzanten** [comment]
@MarcinKuder Do you have some more specific info on which versions this is happening on?
I've just tested the latest from the `develop` branch on Chrome 60 and Firefox 55 on Windows 10  and Chrome 56 on Windows 8, but haven't been able to replicate this issue.

**Comment by rijkvanzanten** [comment]
Thanks for the info @prudolph81!

**Comment by rijkvanzanten** [comment]
I've added @prudolph81's fix in https://github.com/directus/directus/commit/548d5d5142d6803ef6a37b00f11c471549b81472. Please let me know if this commit fixes the issue on your end as well @MarcinKuder

**Comment by MarcinKuder** [comment]
@rijkvanzanten I confirm that the width issue is gone after the fix.
Height can also be set in the same place but I assume that the control shall be resizable? At least this is what the 'Max Height' setting in Interface option suggests. The resize is not working for me.  But it is not a big deal.

And thanks for clarifying the uloaded file chooser question.

**Comment by rijkvanzanten** [comment]
The idea is that the editor changes height to accommodate the height of the content. The `max-height` option allows you to set the max-height it's allowed to grow, to prevent the page being completely covered by a huge editor.

**Comment by MarcinKuder** [comment]
Thanks explanation but my wysiwyg full does not change the height regardless of the content.

**Comment by benhaynes** [comment]
@MarcinKuder – could you provide a screenshot of your interface options?

@rijkvanzanten – any idea why this wouldn't be working?

**Comment by MarcinKuder** [comment]
Screenshots below.
Please note that I have already added 
`div.mce-edit-area iframe {width: 100%; } `
to fix the width issue but the height is still 150px.

I think that 300x150 is just a fallback to defaults for iframe - see https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-height

![image](https://user-images.githubusercontent.com/1597894/29729747-bb14cdbc-89dd-11e7-9c6a-0a2327b07891.png)
![image](https://user-images.githubusercontent.com/1597894/29729750-bfea0398-89dd-11e7-9e83-51eaa0893483.png)
![image](https://user-images.githubusercontent.com/1597894/29729758-cb03bff8-89dd-11e7-94cc-9d9f6bd7d2a1.png)
![image](https://user-images.githubusercontent.com/1597894/29729760-cdc57f06-89dd-11e7-8476-81da11acbe6d.png)

**Comment by rijkvanzanten** [comment]
Okay, just a wild guess here, what happens if you add `height: 100%` to the iframe as well? It might just limit the bounding box size..

**Comment by MarcinKuder** [comment]
Unfortunately, it did not helped.
For now, I just set min-width: 400px; - it is not resizing but it is a least higher than 150.
Thanks.

**Comment by benhaynes** [comment]
What else do we need to do here? Is this an edge-case with a specific/legacy browser? Can we write a conditional to solve it? Let's get this issue resolved, or if there is no resolution we should close it @rijkvanzanten.

**Comment by MarcinKuder** [comment]
If no one else sees the height issue, then you can close it. My main concern was about the width and this was resolved. Thanks!

**Comment by rijkvanzanten** [comment]
I'd like go get this fixed, but I'm not able to reproduce it myself... If anyone has a fix, please let me know 🙂

**Comment by podlebar** [comment]
add to **skin.css** (this is the parent iframe):
`.mce-container iframe { width: 100% }`

**Comment by rijkvanzanten** [comment]
Thanks @podlebar, but that's only for the width right? The fix by @prudolph81 has the same effect I believe. 

Do you happen to know fix for the height not filling as well?

**Comment by podlebar** [comment]
you could give the iframe a min-height.. this could be done via a config of the field (Interface option: Max Height). i don't see how the parent iframe could adjust itself to the child content height.

so i would set min-height and max-height to the value of 'Max Height'

**Comment by rijkvanzanten** [comment]
Yeah that's the thing. It does exactly that on Mac on every browser. Even the same versions of chrome and everything. I haven't been able to reproduce this issue via a virtual machine as well... 🤔 

I rather not hack in a fix just for windows.. I feel like there should be a solution to this to get it platform agnostic

**Comment by benhaynes** [comment]
So what are you thinking for this Rijk? If we can't duplicate, what are good next steps?

**Comment by rijkvanzanten** [comment]
Either find out a way to reproduce this, or wait until someone else comes up with a solution.. Since there are more pressing concerns, I guess it's probably the second

**Comment by michlschmitt** [comment]
I encounter the same issue - as @MarcinKuder described - on the latest Firefox, Safari and Chrome versions. The WYSIWYG Full editor has only 300px width and 150px height and is not resizeable. Any ideas how to proceed?

**Comment by rijkvanzanten** [comment]
This is also on Windows @michlschmitt?

**Comment by michlschmitt** [comment]
@rijkvanzanten nope, I am on MacOS Sierra.

**Comment by podlebar** [comment]
i have this to on macOS Sierra.. and i guess there must be a hack like in every project or a js eventlistener the resizes the iframe to the real width and height with calculations on load and on resize

**Comment by rijkvanzanten** [comment]
Interesting... 

On what branch / version is this @michlschmitt @podlebar?

I didn't have any issues on macOS Sierra or on macOS High Sierra

For full transparency, this is expected behavior (shown on Safari 11.0 macOS High Sierra): 

![2017-09-11 09_38_31](https://user-images.githubusercontent.com/9141017/30277175-fdba5fac-96d4-11e7-9c4b-f0523c2d9e3f.gif)

**Comment by michlschmitt** [comment]
@rijkvanzanten I am on v6.4.2 (Ruby Rabbit) and I use the bundled version.

**Comment by podlebar** [comment]
i'm on 6.4.2 too ... @rijkvanzanten what happens if you ad some other fields like markdown before that field?

**Comment by spotbot2k** [comment]
Same issue on Mac OS 10.12.6 and Firefox 56b11/ Chrome 61. The CSS-fix does help, but vertical resize does not work. @podlebar putting markdown on the same page has no effect - the textarea  itself is not resized as well. Used 6.4.2.

**Comment by rijkvanzanten** [comment]
We've been chasing a ghost here. This is already fixed on the `develop` branch latest which will hit release and master very soon. I just re-installed from pre-build `.zip` and that has the issue mentioned above.

**Comment by michlschmitt** [comment]
I upgraded to the last bundled version (6.4.4) and I still can't resize the editor on Mac with High Sierra. Any updates on this?

**Comment by konradwww** [comment]
The same, cant't resize the wysiwyg full editor with directus version: 6.4.9 on Mac OS X High Sierra, Chrome and Safari.
