### ISSUE TITLE
Translation interface issues + question

### ISSUE THREAD

**Issue by MarcinKuder** [directus/directus#1781]
## Version Info
  - Directus version and branch: directus-build-6.4.2.20170823180744.tar.gz.tgz
  - PHP version: 7.0
  - MySQL version: 5.6.25
  - OS name and version: (client): Windows 10, Chrome

## Expected Behavior
I'm seeing 2 issues with translation tables.

1. Let's say I have 'product' table and 'product_translations', both are linked using Translation interface. There is also 'languages' table with 2 records. 
The issue is that in order to save the records in 'product_translations' table, I have to change the language using the drop-down (eg. from Polish to English). Without touching the dropdown, the record is not created even if I provide values for fields in 'product_translations'. 
When the translation record for selected language is already created, updating the record works fine - no need to switch languages to save translated fields.

2. When there is a mandatory field in 'product_translation' table, the 'required' validation is not triggered when editing the 'product' table record. In other words, it is possible to leave mandatory field from translation table blank even if it is marked as required.
Changing the field with Translation interface to mandatory does not help.

Additionally, one question - what is the purpose of the 'Languages Code Column' in Translation interface options? BTW - the resource description of this option is missing - see screenshot. 

![image](https://user-images.githubusercontent.com/1597894/29997882-181203c6-901f-11e7-9c2c-6398e2ae1c38.png)

Thanks,
Marcin

**Comment by WellingGuzman** [comment]
Hey @MarcinKuder,

Did you try using the `develop` branch? I think that issue was resolved previously (hasn't been released yet).

About the `language_code_column` sorry for the confusion, but this was, (not is right) but will be the column where the language code will be set, example `en` instead of "record id 1" and option if you don't want to use primary as string.

**Comment by MarcinKuder** [comment]
@WellingGuzman thanks for a quick response.

Issue number 1 is indeed fixed when I merged recent changes in TranslationView.js 

Issue number 2 (mandatory fields) is still present. I cannot switch to develop right now, so I cannot validate if it will help.

Thanks,
Marcin

**Comment by WellingGuzman** [comment]
Hey @MarcinKuder, did you mark the column as required? because the issue No. 2, is kind of by design right now, and we are trying to get to a solution to this one https://github.com/directus/directus/pull/1783#issuecomment-327007307

Depends on what we decided it will be done in that PR. either way you are welcome to discuss over there.

I will close this as the main issue is fixed.
