### ISSUE TITLE
Error "ID: Value has to be unique" when migrating schema and data

### ISSUE THREAD

**Issue by hasnainsaad93** [directus/directus#18653]
### Describe the Bug

Error appearing upon creation to a collection after migrating schema and data from one directus instance to another.

![IDValueError](https://github.com/directus/directus/assets/20535381/fda47431-b8ed-4091-9ac6-1162383be2bc)

### To Reproduce

To reproduce this error, two separate instances (Source, Target) of Directus are required.

1- Create a new non singleton collection in Source, make sure primary key is set as auto incremented.
2- Add some records.
3- Take snapshot from Source and find the difference b/w Source and Target.
4- Apply that difference to Target instance.
5- Export data of newly created collection in JSON format from Source.
6- Import data in the same collection in Target instance.
7- Try creating a record, error will appear. 

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
Please make sure you're on the latest version, I believe this was already resolved (https://github.com/directus/directus/issues/18609)👍🏻

**Comment by hasnainsaad93** [comment]
> Please make sure you're on the latest version, I believe this was already resolved ([https://github.com/directus/directus/issues/18609)👍🏻](https://github.com/directus/directus/issues/18609)%F0%9F%91%8D%F0%9F%8F%BB)

I have upgraded both Source and Target, but the issue still persist. Issue referenced here is a different issue, where error says ID value is required, but the error I quoted is "ID: Value has to be unique". This is still not resolved. I have shared the steps to produce above and still reproducing in latest version.
