### ISSUE TITLE
Update available: 10.1.0 -> 11.0.1 but latest version since 5 days is 10.2.1

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18782]
### Describe the Bug

When running `npx directus start` we get a wrong version to update to.

### To Reproduce

run `npx directus start` in the console

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This was fixed in 10.2.0 with https://github.com/directus/directus/issues/18782

**Comment by Pachat** [comment]
@br41nslug OK. But there is still a problem with `npx directus -v`
On a clean install of `10.2.0` with `10.2.0` correctly shown in the UI, and correctly no request for update after `npx directus start`
`npx directus -v` still gives `11.0.1` on my development computer.

**Comment by Pachat** [comment]
> This was fixed in 10.2.0 with https://github.com/directus/directus/issues/18782

#18782 is referencing the present issue

**Comment by br41nslug** [comment]
Oops copy-pasted the wrong link 😇 i meant it was fixed by https://github.com/directus/directus/pull/18738

Let's track the `npx directus -v` part of this in your new issue :) https://github.com/directus/directus/issues/18795
