### ISSUE TITLE
Extensions Loading But Not Creating Menu Item

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#19326]
### Describe the Bug

Seems like in 10.5.2 extensions that create a menu item in the data studio isnt showing anymore. 

Seems to be affecting all that require it.

First noticed this issue earlier today:
https://github.com/maltejur/directus-extension-generate-types/issues/32

And than confirmed myself when installing the awesome: https://github.com/baguse/directus-extension-flow-manager

### To Reproduce

Install an extension that create a menu item in data studio.

Menu item doesn't appear, but you can still manually reach extension page. 

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Might this be related to #19250 ? But that got fixed in v10.5.1 and for me on v10.5.2 they do show up both in the settings and on the sidebar: 
![image](https://github.com/directus/directus/assets/14810858/75828537-69db-4e99-8757-4b2cdcdd1b5c)

I tested the bundle-type extension and that seems to work.

**Comment by BlackDahlia313** [comment]
I can try another redeploy and clearing build cache to see if that wiggles it

**Comment by BlackDahlia313** [comment]
Not sure what DO did to my deploy, but after forcing another and a successful deployment, the menu item is still missing.

**Comment by DanielBiegler** [comment]
What do you mean by

> I can manually add one

You mean you can reach it directly via URL?

For me it works like intended: just created a module, linked it, enabled in settings, now it shows up. Can't reproduce your error.

| Settings | Data Studio |
|--------|--------|
| ![image](https://github.com/directus/directus/assets/14810858/e544d6b7-8f08-45ec-b4f5-abec854126f3) | ![image](https://github.com/directus/directus/assets/14810858/f43a96d0-a0d5-4502-a5d8-bd7835466564) |

**Comment by paescuj** [comment]
Can you please check the browser console for any errors?

**Comment by BlackDahlia313** [comment]
> 

Nothing in console. No errors. Just tried on 10.5.3 reinstalling the flow manager extension and no menu item created. If you know how to make a menu item, its fine, but for some... lol

**Comment by paescuj** [comment]
This one seems to be particularly difficult to reproduce. Just tested again using the Docker image v10.5.3 and the flow manager extension by following the installation from https://docs.directus.io/self-hosted/docker-guide.html#adding-packages-to-use-in-flows-scripts.
The menu item appeared in Firefox as well as Chromium.

Some questions that may provide a little clarity:
How did you install the extension? Which browser are you using? Do you have any special configuration or e.g. a proxy in between? Is this happening as well with a fresh Directus installation?

**Comment by BlackDahlia313** [comment]
@paescuj 

Installing extensions via dockerfile. Using chrome, firefox and edge to test. And no its pure docker in DO apps. No proxy. Have not tried on a fresh install yet.

This maybe related:

https://discord.com/channels/725371605378924594/1139933556404146206

**Comment by DanielBiegler** [comment]
So I tried to reproduce this again under `v10.7.2` with npm and Dockerfile as installation method but cant reproduce.

Dockerfile:

```Dockerfile
FROM directus/directus:10.7.2

USER root
RUN corepack enable
USER node

RUN pnpm install directus-extension-flow-manager
```

Which builds fine, then I tried **both** a fresh install and plugging in an existing database without the extension.

```
# docker run --rm -it -p 8080:8055 -v database:/directus/database -e TELEMETRY=false -e KEY=$(uuidgen) -e SECRET=$(uuidgen) local/directus-extension-test
[18:58:08.450] INFO: Loaded extensions: directus-extension-flow-manager
[18:58:08.455] INFO: Initializing bootstrap...
[18:58:08.457] INFO: Database already initialized, skipping install
[18:58:08.457] INFO: Running migrations...
[18:58:08.462] INFO: Done
2023-11-13T18:58:08: PM2 log: Launching in no daemon mode
2023-11-13T18:58:08: PM2 log: App [directus:0] starting in -cluster mode-
2023-11-13T18:58:11: PM2 log: App [directus:0] online
[18:58:13.568] INFO: Loaded extensions: directus-extension-flow-manager
[18:58:13.577] WARN: PUBLIC_URL should be a full URL
[18:58:13.579] WARN: Spatialite isn't installed. Geometry type support will be limited.
[18:58:13.606] INFO: Server started at http://0.0.0.0:8055
```

It shows up successfully under the logs and for both scenarios everything works just as expected.

![image](https://github.com/directus/directus/assets/14810858/b65ee989-235f-43be-8f44-da9dbe4730bd)

I think I'll close this now since we tested this multiple times and we sadly have no further reproduction steps. If @BlackDahlia313 or someone else has reproduction steps please let us know and we can reopen / create a new issue. Thanks!

**Comment by paescuj** [comment]
> I think I'll close this now since we tested this multiple times and we sadly have no further reproduction steps. If @BlackDahlia313 or someone else has reproduction steps please let us know and we can reopen / create a new issue. Thanks!

Makes sense to me 👍 Also had a quick look over the relevant code, and couldn't find any obvious issues.
