### ISSUE TITLE
Table with 'Many-to-one' to Files, is not returning file data if limit above 204

### ISSUE THREAD

**Issue by dlaprade** [directus/directus#1950]
## Version Info
  - Directus version and branch: 6.4.3
  - PHP version: 7.1.11
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS name and version: Debian Jessie Linux

## Expected Behavior
I have a table that contains a 'many-to-one' relationship to files and when I search using the API I expect the related file information to be returned for all rows.

## Actual Behavior
The 'many-to-one' relationship to files is return null.

## Steps to Reproduce
 1. Create simple table with Many-to-one to files
 2. Add over 204 entries in table
 3. provide search that returns more than 204 rows
 4. notice that some records have the many-to-one relation as null

## Schema Dump, Logs, or Screenshots
<img width="344" alt="screen shot 2017-11-10 at 1 27 14 pm" src="https://user-images.githubusercontent.com/7399336/32679341-fca0bc72-c61a-11e7-94b3-444ab4e326ca.png">

**Comment by rijkvanzanten** [comment]
I'm wondering if the limit on 200 is a bug or a feature.. I can imagine fetching all the related items of so many records will take quite a while to finish.

Could you enlighten us with some wisdom @WellingGuzman?

**Comment by benhaynes** [comment]
Also, does this happen even when using the `limit` and `offset` params?

https://api.getdirectus.com/1.1/#Get_Files

**Comment by dlaprade** [comment]
I have verified it still happens when using both limit and offset parameters.

**Comment by WellingGuzman** [comment]
I may bet this has to do with the limit bug we "fixed" previously.
@dlaprade would it be possible for you to test this using `develop` branch? just to make sure we have gone to far without updating to 6.4.4 (which we know)

**Comment by dlaprade** [comment]
@WellingGuzman I am not able to reproduce the issue on the development branch.

**Comment by WellingGuzman** [comment]
Thanks @dlaprade for confirming.

For future reference, this issue is fixed on `6.4.4`

**Comment by theideaofnorth2** [comment]
Hello dear directus team,

I am using
- directus 6.4.4
- directus php sdk 1.0

And I am still seeing this issue when making a request from the php sdk (with the odd limit of 204 items).
However, when I request the tables from directus itself (not from the php sdk), the issue doesn't occur. Should the php sdk also be updated to have the bug fix?

Thanks,
Vincent

**Comment by vkammerer** [comment]
Hello,

Should this issue be reopened? I am still having the same issue as @theideaofnorth2

**Comment by rijkvanzanten** [comment]
@WellingGuzman Can you confirm if this has been fixed in the meantime (in either the current _or_ next version of the API)?

**Comment by vkammerer** [comment]
I just tested it and I'm not getting the bug anymore

**Comment by rijkvanzanten** [comment]
Ah! Thanks :)
