### ISSUE TITLE
BigInt primary key routing in the App

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20288]
### Describe the Bug

When using a BigInt primary key for a collection the App will fail to route these IDs when they go beyond regular numbers which is exactly what you would use a BigInt for.

https://github.com/directus/directus/assets/9389634/cb5d0881-52e2-43b4-a4b0-dd529fff3441

### To Reproduce

- create a collection with a BigInt primary key
- create some records with IDs `> 9007199254740991` or `< -9007199254740991`
- try to open the detail page

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
I wasn't able to reproduce this on my end.
Are you still able to do so @br41nslug? If so, does it depend on the DB? I tested against SQLite & Postgres.
Otherwise might have been fixed by the recent update of Knex or DB drivers.

**Comment by br41nslug** [comment]
Still reproduceable on my end using Postgres both on 10.8.2 and on `main` (production)

**Comment by br41nslug** [comment]
@paescuj I dont think this is database specific but rather a Js issue. Did you test with large enough numbers? specifically outside the range that `Number` can handle which would require a bigint type like `9223372036854775807`

**Comment by paescuj** [comment]
Yep, thought the same 👍 Thanks, will test again with super large number 😄

**Comment by paescuj** [comment]
Okay, can confirm now 👍 The number indeed needs to be high enough.

**Comment by br41nslug** [comment]
Awesome, yeah else it will just happily cast it to `Number` and things just work 😄
