### ISSUE TITLE
[SDK] Unable to subscribe(), failed to execute 'send' on 'WebSocket': Still in CONNECTING state

### ISSUE THREAD

**Issue by gremo** [directus/directus#20628]
### Describe the Bug

I get this error while trying to subscribe() using the SDK, following the official [realtime docs](https://docs.directus.io/packages/@directus/sdk/#real-time). The error is coming from `composable.ts`:

> Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
> composable.ts:244

Looking at the code:

```ts
async subscribe<Collection extends keyof Schema, const Options extends SubscribeOptions<Schema, Collection>>(
  collection: Collection,
  options = {} as Options
) {
  if (!socket || socket.readyState !== WebSocketState.OPEN) await this.connect();
  if ('uid' in options === false) options.uid = uid.next().value;

  let subscribed = true;
  const ws = socket!;
  const send = (obj: Record<string, any>) => ws.send(JSON.stringify(obj));

  send({ ...options, collection, type: 'subscribe' }); // <-------- ERROR LINE IS THIS
```

I've also tryed to `connect()` just before `subscribe()` but I get the same error.

### To Reproduce

Create a client:

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  createDirectus,
  authentication,
  rest,
  realtime,
  DirectusClient,
  RestClient,
  WebSocketClient,
} from "@directus/sdk";

export default createDirectus("https://directus.example.com")
  .with(authentication("json"))
  .with(rest())
  .with(
    realtime({
      authMode: "public",
    })
  ) as DirectusClient<any> & RestClient<any> & WebSocketClient<any>;

```

Import the client and try to `subscribe()` to a collection:

```ts
import directusClient from "./directusClient";

await directusClient.subscribe("message", {
  query: { fields: ["*"] },
});
```

### Directus Version

13.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gremo** [comment]
I've followed the official example in pure JavaScript using  `new WebSocket` before ever trying to use the SDK, just to check that all was working fine..

I'm able to connect yes. I can also expose the public URL if you want it, it's just a test server.

**Comment by br41nslug** [comment]
Can you update you SDK snippet to include how you used authentication and the explicit `.connect()` call? presuming that the collection mentioned is not publicly accessible. Because the shared "plain JS" and "sdk" snippets are not doing the same things.

**Comment by gremo** [comment]
Here is my findings: I still thing there is something wrong in some behaviours of the SDK. I'm speding the all day to make this work without success:

1. Scenario 1: SDK with `staticToken` and `authMode: "handshake"`: not working, getting "DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.":

![image](https://github.com/directus/directus/assets/1532616/59af6aee-c9d4-4ca7-933a-5fd02314759c)


```js
  useEffect(() => {
    const subscribe = async () => {
      await directusClient.subscribe("message", {
        query: { fields: ["*"] },
      });

      directusClient.onWebSocket("open", () => console.log("open"));
      directusClient.onWebSocket("error", () => console.log("error"));
      directusClient.onWebSocket("message", (message) =>
        console.log("[WS] Message", message)
      );
    };

    subscribe();
  }, []);
```

2. Scenario 2: SDK with `staticToken` and `authMode: "handshake"` with `connect()` and a delay: working:

```js
  useEffect(() => {
    const subscribe = async () => {
      await directusClient.connect();
      setTimeout(() => {
        directusClient.subscribe("message", {
          query: { fields: ["*"] },
        });
      }, 3000);

      directusClient.onWebSocket("open", () => console.log("open"));
      directusClient.onWebSocket("error", () => console.log("error"));
      directusClient.onWebSocket("message", (message) =>
        console.log("[WS] Message", message)
      );
    };

    subscribe();
  }, []);

```
![image](https://github.com/directus/directus/assets/1532616/ddab7041-c999-4e9c-b1b3-0f71309124e4)

3. Scenario 3: SDK without a token and `authMode: public`: not working, getting "Authentication handshake failed.", even if the collection is public.

![image](https://github.com/directus/directus/assets/1532616/964b3039-2b01-4e54-a3fb-d5d114ada053)

**Comment by br41nslug** [comment]
The race condition between authenticating and subscribing is known unfortunately and has another ticket somewhere, this is generally solved by explicitly calling connect.

So scenario 1 and 2 are on the right track:
```js
const subscribe = async () => {
      await directusClient.connect();

      directusClient.onWebSocket("open", () => console.log("open"));
      directusClient.onWebSocket("error", () => console.log("error"));
      directusClient.onWebSocket("message", (message) =>
        console.log("[WS] Message", message)
      );

      const { subscription } = directusClient.subscribe("message", {
          query: { fields: ["*"] },
        });
      }, 3000);

    
    };

    subscribe();
```

> Scenario 3: SDK without a token and authMode: public: not working, getting "Authentication handshake failed.", even if the collection is public.

The connection is only `public` if configured so on the server side, the SDK just uses it as to decide whether it needs to authenticate while connecting, after connecting or not at all. You cannot set the SDK authMode lower than the authMode configured on the server or you will always get auth errors.

**Comment by gremo** [comment]
@br41nslug so basically my issue is just another issue on a known problem?

By the way, calling `connect()` doesn't solve the issue at all, I'll try to put a test file somewhere in a while. Only `setTimeout` seems to solve the issue.

> The connection is only public if configured so on the server side, the SDK just uses it as to decide whether it needs to authenticate while connecting, after connecting or not at all. You cannot set the SDK authMode lower than the authMode configured on the server or you will always get auth errors.

What do you mean authMode configured on the server? You mean using the GUI and setting the collection properties?

**Comment by br41nslug** [comment]
Closing this issue for now as i am unable to reproduce it with the provided information. There is a non-zero chance this will be resolved by #20635 which attempts to solve the race condition.

**Comment by gremo** [comment]
@br41nslug thanks for helping. While i've solved my issues regarding the authentication (thanks to the env variable link) I'm stil getting the race conditions.

So the race conditions remains but I hope they get fixed by your PR.
