### ISSUE TITLE
Unable to access installer of Directus 7.0.6

### ISSUE THREAD

**Issue by jameswill** [directus/directus#2242]
I tried installing 7.0.6 on my test server with php 7.0 and mysql 5.5. I am installing Directus suite where API and CMS both are combined. I have downloaded zip package from [https://github.com/directus/directus/releases](url)

I am not getting installer on visiting http://{url}/{to}/directus706/public/admin, instead it is redirecting to http://{url}/{to}/directus706/public/admin/#/login (login page)

I also tried filling database details in config/api.php and visiting /public/admin for installer. However this also results in redirection to login page.

**Comment by shealavington** [comment]
Fill in the database in `./config/api.php` then import the sql from `./src/schema.sql` to manually install.

You're landing on the right page it should redirect where it did but it should show an install button, I had that same issue on my server, but did a manual install and it worked 👍

**Comment by sebj54** [comment]
Possible duplicate?
https://github.com/directus/directus/issues/2238

**Comment by shealavington** [comment]
Don't think so seb, he didn't mention errors. He just didn't get an install button and during manual install he didn't say he imported the sql.

**Comment by sebj54** [comment]
Actually, I have the same behavior than him. I have nothing when hitting the public root and when I'm visiting admin, I am redirected to the login screen. 
I assume he didn't have errors because his server is configured to add them in a log file. But maybe I'm wrong and it's a totally different problem!

**Comment by shealavington** [comment]
That's the correct behaviour, you should land on the login page.

**Comment by sebj54** [comment]
Yes, sure, I know that. Maybe I didn't make myself clear: the issue is that he can't (and anyone can't I guess) access the installer. He and I talked about the admin route because this is the only thing accessible after cloning the repo.

**Comment by shealavington** [comment]
> he can't (and anyone can't I guess) access the installer.

That makes sense, however saying "it redirects me to the login" doesn't, as the installer is on the login page, therefore it would be correct to be on the login page. I'm with you now.

**Comment by jameswill** [comment]
> 
> 
> Fill in the database in `./config/api.php` then import the sql to your database from `./src/schema.sql` to manually install.
> 
> You're landing on the right page it should redirect where it did but it should show an install button, I had that same issue on my server, but did a manual install and it worked 👍

Yes. It did solves the issue. However ideally installer should run to install the script.

Also when I explicitly visit /public post importing database, it gives me a blank page. Further checking my error log, it says, Array ( [type] => 1 [message] => Interface 'Monolog\ResettableInterface' not found [file] => {Path}/{To}/directus706/vendor/monolog/monolog/src/Monolog/Logger.php [line] => 28 )  it should redirect to /public/admin when I visit /public

**Comment by shealavington** [comment]
Glad it worked, and yes, I agree, it should, there must be a bug in the latest release, which I know is being looked into 👍

> It should redirect to /public/admin when I visit /public

That's not the case, upon visiting `/public` you're at the API, but when you visit `/public/admin` you're loading the GUI. 

-

Sometimes it's hard to know where someone went wrong with an install, because they explain what they expect to heppen, which sounds like the problem, because it isnt what should happen.

It's like, the installer is on the login page, so saying "it redirects me to the login" to you might seem unnatural, but is the default behaviour which is why I got confused. 😂👍

**Comment by sebj54** [comment]
@jameswill Maybe you can try this fix? https://github.com/directus/directus/issues/2238#issuecomment-437937471

@shealavington I know it can be confusing! Would you want a video so you can follow the install process? 😄 I'll try to make it clearer now: 

The fact is, when we are redirected to the admin login page, we don't have any credential to log in. The only thing we did before is cloning the repo (or directly downloading the release zip) and browsing the `/public` route like it is stated in the documentation: https://github.com/directus/docs/blob/master/install.md.

I just figured out that there are 2 versions for the documentation:
https://github.com/directus/docs/blob/master/install.md and https://docs.directus.io/app/admin/install.html#installation.

The first one indicates this method: 

```sh
git clone https://github.com/directus/directus.git
```

and the second one: 

```sh
git clone -b build https://github.com/directus/app.git directus
```

I did the first one on my installation and I had the same problem than @jameswill. Once I applied the fix I described in the other issue, I accessed to the installer and was able to enter my DB credentials and configure Directus.

I just tried the second method and then, I have an already configured Directus. It uses an external API (which I didn't want). By chance, I knew the credentials because I guessed it was the the same as on the demo. 
Now, I just don't know how to connect this instance to my local DB.

I think there are two issues now: a problem with a dependency and a fragmented and incomplete documentation 😐

**Comment by rijkvanzanten** [comment]
If I install the api clean from the master branch and install the composer dependencies fresh, it seems to work just fine. This indicates that either something got accidentally ignored in Git during the build process or I just downloaded a newer version of a broken package. Either way, I'll release a new version with this issue fixed shortly

**Comment by rijkvanzanten** [comment]
We started adding the `.gitignore` file of the main master branch to the builds as well, in order to prevent the logs from being tracked. However, this would also ignore _changes_ in `/vendor`. I didn't catch this before because it seemingly didn't touch `/vendor`, except of course when this one nested dependency updated and it didn't make it into build.

**Comment by rijkvanzanten** [comment]
Fixed in [`v7.0.7`](https://github.com/directus/directus/releases/tag/v7.0.7)

**Comment by lhardie** [comment]
Perhaps I'm doing something wrong, but I am still experiencing this issue with v7.0.7.  

First, I tried what the docs said and just cloned the git repo, and hit the admin url.  However, this gives me the login with an error that says "Couldn't reach API", and the fields are disabled, so I cannot attempt a login.

Then, I used the link from rijkvanzanten to grab the tar file itself instead.  I extracted the files, then manually configured by creating and editing the api.php file myself, then imported the database schema.  Then, I hit the admin url again, and I still get the same error.

Am I missing a step or something?
