### ISSUE TITLE
Error loading files

### ISSUE THREAD

**Issue by gloribus** [directus/directus#23266]
### Describe the Bug

Errors are displayed when trying to upload a file. Both an avatar and via admin/files

```
{
  "errors": [
    {
      "message": "Validation failed for field \"uploaded_on\". Value is required.",
      "extensions": {
        "field": "uploaded_on",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    }
  ]
}
```

### To Reproduce

/admin/files/+
Upload image or file

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MariaDB 10.6.18

**Comment by hanneskuettner** [comment]
Do you have any custom permissions set for the `directus_files` collection or any filter hooks that might prevent creation?

**Comment by gloribus** [comment]
> Do you have any custom permissions set for the `directus_files` collection or any filter hooks that might prevent creation? Uploading with an admin account works fine for me locally.

For user policy
<img width="790" alt="image" src="https://github.com/user-attachments/assets/712df819-5b8b-4dac-b7dc-77041fb1e4d7">

I have an error with the admin account too

**Comment by hanneskuettner** [comment]
You having the problem with an admin account as well make me think there is a filter hook or hook extension in play? Can you verify if that is the case?

**Comment by gloribus** [comment]
There are no hooks associated with files
```
[14:15:53] GET /files?filter[_and][0][type][_nnull]=true&filter[_and][1][folder][_null]=true&aggregate[countDistinct]=id 304 14ms
[14:15:53] GET /files?aggregate[countDistinct]=id 304 13ms
[14:15:53] GET /files?limit=25&fields[]=id&fields[]=modified_on&fields[]=type&fields[]=title&fields[]=type&fields[]=filesize&sort[]=-uploaded_on&page=1&filter[_and][0][type][_nnull]=true&filter[_and][1][folder][_null]=true 304 12ms
[14:15:53.184] TRACE: [0.977ms] select 1 from `directus_sessions` where `token` = ? and `user` = ? and `share` is null and `expires` >= ? limit ? [AqtrnoiCkINFDInJIs-VVOCxwWiNHO2i_JvIkUTSyqDdgykzwYGzWc-_5H2yKUXs, 6882146f-0f03-4926-b699-94fda6fc45ae, Fri Aug 09 2024 14:15:53 GMT+0300 (Moscow Standard Time), 1]
[14:15:53.194] TRACE: [1.263ms] select count(`directus_files`.`id`) as `countDistinct->id` from `directus_files` where (`directus_files`.`type` is not null and `directus_files`.`folder` is null) limit ? [100]
[14:15:53.216] TRACE: [1.006ms] select 1 from `directus_sessions` where `token` = ? and `user` = ? and `share` is null and `expires` >= ? limit ? [AqtrnoiCkINFDInJIs-VVOCxwWiNHO2i_JvIkUTSyqDdgykzwYGzWc-_5H2yKUXs, 6882146f-0f03-4926-b699-94fda6fc45ae, Fri Aug 09 2024 14:15:53 GMT+0300 (Moscow Standard Time), 1]
[14:15:53.225] TRACE: [2.953ms] select count(`directus_files`.`id`) as `countDistinct->id` from `directus_files` limit ? [100]
[14:15:53.226] TRACE: [1.525ms] select 1 from `directus_sessions` where `token` = ? and `user` = ? and `share` is null and `expires` >= ? limit ? [AqtrnoiCkINFDInJIs-VVOCxwWiNHO2i_JvIkUTSyqDdgykzwYGzWc-_5H2yKUXs, 6882146f-0f03-4926-b699-94fda6fc45ae, Fri Aug 09 2024 14:15:53 GMT+0300 (Moscow Standard Time), 1]
[14:15:53.234] TRACE: [1.004ms] select `directus_files`.`id`, `directus_files`.`modified_on`, `directus_files`.`type`, `directus_files`.`title`, `directus_files`.`filesize` from `directus_files` where (`directus_files`.`type` is not null and `directus_files`.`folder` is null) order by `directus_files`.`uploaded_on` desc limit ? [25]
[14:15:53] PATCH /users/me/track/page 204 14ms
[14:15:53.578] TRACE: [1.083ms] select 1 from `directus_sessions` where `token` = ? and `user` = ? and `share` is null and `expires` >= ? limit ? [AqtrnoiCkINFDInJIs-VVOCxwWiNHO2i_JvIkUTSyqDdgykzwYGzWc-_5H2yKUXs, 6882146f-0f03-4926-b699-94fda6fc45ae, Fri Aug 09 2024 14:15:53 GMT+0300 (Moscow Standard Time), 1]
[14:15:53.586] TRACE: [0.831ms] update `directus_users` set `last_page` = ? where `id` in (?) [/files/+, 6882146f-0f03-4926-b699-94fda6fc45ae]
[14:15:56] POST /files 400 13ms
[14:15:56.953] TRACE: [0.901ms] select 1 from `directus_sessions` where `token` = ? and `user` = ? and `share` is null and `expires` >= ? limit ? [AqtrnoiCkINFDInJIs-VVOCxwWiNHO2i_JvIkUTSyqDdgykzwYGzWc-_5H2yKUXs, 6882146f-0f03-4926-b699-94fda6fc45ae, Fri Aug 09 2024 14:15:56 GMT+0300 (Moscow Standard Time), 1]
[14:15:56.960] TRACE: [0.525ms] select `storage_default_folder` from `directus_settings` limit ? [1]
[14:15:56.962] DEBUG: Validation failed for field "uploaded_on". Value is required.
    err: {
      "type": "",
      "message": "Validation failed for field \"uploaded_on\". Value is required.",
      "stack":
          DirectusError: Validation failed for field "uploaded_on". Value is required.
              at file:///home/reflex/VOX/IS/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:68:60
              at Array.map (<anonymous>)
              at file:///home/reflex/VOX/IS/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:68:43
              at Array.map (<anonymous>)
              at processPayload (file:///home/reflex/VOX/IS/node_modules/@directus/api/dist/permissions/modules/process-payload/process-payload.js:68:14)
              at file:///home/reflex/VOX/IS/node_modules/@directus/api/dist/services/items.js:125:25
              at file:///home/reflex/VOX/IS/node_modules/@directus/api/dist/utils/transaction.js:18:52
              at /home/reflex/VOX/IS/node_modules/knex/lib/execution/transaction.js:233:22
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "name": "DirectusError",
      "extensions": {
        "field": "uploaded_on",
        "type": "required"
      },
      "code": "FAILED_VALIDATION",
      "status": 400
    }

**Comment by gloribus** [comment]
Now it is impossible to even change the project logo. On RC3 it was possible

**Comment by gloribus** [comment]
<img width="899" alt="image" src="https://github.com/user-attachments/assets/447004dd-2f71-4c68-a261-00ee17278ae7">
I don't know if it's a database issue or an update from RC3 but the default value was zero. Manual correction to current_timestamp() helped

**Comment by ddalledo** [comment]
I ended up having the same issue with 11.0.1 and solved with @gloribus patch. I don't see any changes related to this to the 11.0.2 so I am guessing the problem is still present.

**Comment by oidt** [comment]
having the same issue on 11.0.0

**Comment by hanneskuettner** [comment]
Can you provide us with more information? Are you also using MariaDB? Which DB version? Were there any migrations that failed when upgrading from Directus 10 to Directus 11?

**Comment by oidt** [comment]
Server version: 11.4.2-MariaDB-ubu2204 - mariadb.org binary distribution
I see this two migrations:
<img width="296" alt="image" src="https://github.com/user-attachments/assets/8beb7534-ca93-40ad-8512-1995d0d56b80">
not sure how to check if they failed or not, one looks like 'fixing the uploaded_on' ?

**Comment by jjeising** [comment]
This issue already exists in 10.13.2 with a fresh database.

**Comment by vitorgabrieldevk** [comment]
> Versão do servidor: 11.4.2-MariaDB-ubu2204 - distribuição binária mariadb.org Vejo essas duas migrações: não tenho certeza de como verificar se elas falharam ou não, uma parece 'corrigindo o uploaded_on'? <img alt="imagem" width="296" src="https://private-user-images.githubusercontent.com/17176500/362204704-8beb7534-ca93-40ad-8512-1995d0d56b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjkyNDIsIm5iZiI6MTcyNTQ2ODk0MiwicGF0aCI6Ii8xNzE3NjUwMC8zNjIyMDQ3MDQtOGJlYjc1MzQtY2E5My00MGFkLTg1MTItMTk5NWQwZDU2YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE2NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YjZmY2Q5NmQ2ZTM0YTUyYmVjY2ViNjkwMjBlYjY5NmEwMmZjM2UyYTdmMmM1MzYxMGEyMDY0YWQ0ZDMwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kxz7C2P0QiMFhDLBlGG1t3NNgzWcUItI_vKRhULWN28">
> 
> é assim que a tabela está agora: <img alt="imagem" width="377" src="https://private-user-images.githubusercontent.com/17176500/362206096-20823ec4-8896-4a27-9b19-c023cf4091a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjkyNDIsIm5iZiI6MTcyNTQ2ODk0MiwicGF0aCI6Ii8xNzE3NjUwMC8zNjIyMDYwOTYtMjA4MjNlYzQtODg5Ni00YTI3LTliMTktYzAyM2NmNDA5MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE2NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNjg2M2M1Njk0ZTliY2VjOGZhYmY4MTc5MTk1ODY0ZjQ4NDc5NjU3NWM2NmE1YzVhZWE5OWFiZGQ5MWExNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3k5doi_fa3WouvzLqNX0m09juKMqhqmi9-2aGqiaXRI">
> 
> ```
> {
>   "errors": [
>     {
>       "message": "Validation failed for field \"uploaded_on\". Value is required.",
>       "extensions": {
>         "field": "uploaded_on",
>         "type": "required",
>         "code": "FAILED_VALIDATION"
>       }
>     }
>   ]
> }
> ```
> 
> depois de trocar a mesa: `` ALTER TABLE `directus_files` CHANGE `uploaded_on` `uploaded_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP; ``
> 
> e reiniciando o directus ele está funcionando novamente para mim também!

Está solução funcionou para mim!

**Comment by tanero** [comment]
same issue still exist on directus version 11.1.0 with default install on mariadb (10.5.22).

**Comment by medunea** [comment]
在 11.1.0 上遇到同样的问题

**Comment by valery** [comment]
same issue on 11.1.1

**Comment by paescuj** [comment]
If this still a problem for you, please create a new issue and provide as much information as possible. Thank you!

**Comment by tanero** [comment]
> If this still a problem for you, please create a new issue and provide as much information as possible. Thank you!

What is the benefit of opening a duplicate ticket?

**Comment by tanero** [comment]
The fact that other people are reporting this bug shows that this is still an ongoing issue and should be taken seriously.

**Comment by mvillamizar74** [comment]
> <img alt="image" width="899" src="https://private-user-images.githubusercontent.com/8048487/356574463-447004dd-2f71-4c68-a261-00ee17278ae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjgzMzEsIm5iZiI6MTcyODkyODAzMSwicGF0aCI6Ii84MDQ4NDg3LzM1NjU3NDQ2My00NDcwMDRkZC0yZjcxLTRjNjgtYTI2MS0wMGVlMTcyNzhhZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTc0NzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg3OGVjNjlkNDVlMDM4ZTJhZWM1ZGM2MDIwZmZlNzJhYzg4OTNlYjdlMmEzOGVhYjgyNjU2MTU0YjExMzcwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NdsqamL0JFq7CWLDtxifhdh79iapecyGjN4AabCZVb8"> I don't know if it's a database issue or an update from RC3 but the default value was zero. Manual correction to current_timestamp() helped

It worked for me as well

**Comment by vuhoanglam** [comment]
{
    "errors": [
        {
            "message": "Validation failed for field \"uploaded_on\". Value is required.",
            "extensions": {
                "field": "uploaded_on",
                "type": "required",
                "code": "FAILED_VALIDATION"
            }
        }
    ]
}

same issue

**Comment by mvillamizar74** [comment]
> { "errors": [ { "message": "Validation failed for field "uploaded_on". Value is required.", "extensions": { "field": "uploaded_on", "type": "required", "code": "FAILED_VALIDATION" } } ] }
> 
> same issue

@vuhoanglam , please see the following post, it shows how to solve it - [LINK](https://github.com/directus/directus/issues/23659#issuecomment-2411932700)

**Comment by mvillamizar74** [comment]
> > > { "errors": [ { "message": "Validation failed for field "uploaded_on". Value is required.", "extensions": { "field": "uploaded_on", "type": "required", "code": "FAILED_VALIDATION" } } ] }
> > > same issue
> > 
> > 
> > @vuhoanglam , please see the following post, it shows how to solve it - [LINK](https://github.com/directus/directus/issues/23659#issuecomment-2411932700)
> 
> Thank you, just fixed it, but i still think we need a patch for mariadb

Absolutely!

**Comment by robertgroot-paqt** [comment]
Still an issue with 11.3.2. For whatever reason the result of the migration is incorrect as it puts a zero date in the default. Running the same migration once more does fix it....

To fix it automatically, put the following as a custom migration:

```js
export async function up(knex) {
    await knex.schema.raw(
        'ALTER TABLE `directus_files` CHANGE `uploaded_on` `uploaded_on` TIMESTAMP NOT NULL DEFAULT current_timestamp();',
    );
}

export async function down(knex) {}
```

**Comment by rijkvanzanten** [comment]
> > If this still a problem for you, please create a new issue and provide as much information as possible. Thank you!

> What is the benefit of opening a duplicate ticket?

@tanero Oftentimes — even though the symptoms are the same — the root cause is different. This is especially true if it was reported against an older version, or if the original report doesn't have clear reproduction steps (like is the case here). Secondly, there's thousands of closed issues in this repo alone. We prioritize and organize open issues by various metrics like creation date, version on which it was reported, labels, etc. Re-opening previously resolved or closed issues that are tangentially related wrecks our ability to keep these issues somewhat organized.

**Comment by nicam** [comment]
Hi there,

The issue still persists in `directus:11.3.5`. The issue is the following:

The migration here: https://github.com/directus/directus/blob/main/api/src/database/migrations/20240716A-update-files-date-fields.ts#L5

Renames `uploaded_on` to `created_on` which is fine. But what is missing is that the new column `uploaded_on` that is created afterwards, has NO default.

On Line 17: https://github.com/directus/directus/blob/main/api/src/database/migrations/20240716A-update-files-date-fields.ts#L17 the new field is created without a default:

```js
	await knex.schema.alterTable('directus_files', (table) => {
		table.timestamp('uploaded_on');
	});
```

On mysql, the resulting field looks like this:

```sql
  `uploaded_on` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
```

Where it should be:
```sql
  `uploaded_on` timestamp NOT NULL DEFAULT current_timestamp(),
```

**Comment by iksent** [comment]
**This is how I fixed it (MariaDB)**

0. Login to your MySQL/MariaDB database; `use <database_name>;`

1. Check if problem really exists: `describe directus_files;`

```uploaded_on       | timestamp        | NO   |     | 0000-00-00 00:00:00``` <<< this is a bug

2. Fix:
```
ALTER TABLE directus_files MODIFY COLUMN uploaded_on timestamp NOT NULL DEFAULT current_timestamp();
```

3. Check problem solved: `describe directus_files;`

```uploaded_on       | timestamp        | NO   |     | current_timestamp()```

**Comment by rjamesnw** [comment]
I had the same issue with a fresh install just now, and thank god the fix by @iksent worked! Thanks. 😊

**Comment by sksar** [comment]
This bug still persists. The solution is the fix by @iksent 
`ALTER TABLE directus_files MODIFY COLUMN uploaded_on timestamp NOT NULL DEFAULT current_timestamp();`

And then restart your directus;

**Comment by themegabyte** [comment]
Exists in: directus/directus:11.6.1, the above fix worked.
