### ISSUE TITLE
Files interface issues in 190607A

### ISSUE THREAD

**Issue by autr** [directus/directus#2391]
# Bug Report

## Steps to Reproduce

** Create Collection **

1. Install fresh instance of Directus release 190607A (wget && unzip)
2. Log into admin panel
3. Add new collection “posts”
4. Added field “media” using Files interfaces
5. Set "media" Junction Collection to Auto-generate

** Create Item with an upload **

1. Create new Post
2. Upload image via New File button - when % dialog finishes, JS console logs; `Invalid attempt to spread non-iterable instance at f (nonIterableSpread.js:2)` and image does not appear in Files interface
3. Click Existing and select the uploaded image 
4. Click Save, and image appears in Files interface
5. Click Save on new Post Item

** Edit Item with an upload **

1. Go to list of Posts 
2. Open the Item that was just added; 
3. Files interfaces is blank, and neither buttons are visible
4. JS console logs: `vue.runtime.esm.js:1888 TypeError: Cannot read property 'id' of null  at input.vue:172`

## Expected Behavior

Files appear after uploading.
Files appear when editing an Item.
API returns files as child fields.

## Actual Behavior

File doesn't appear in interface after uploading, but is visible using Existing dialog.
Editing an item and the Files interface does not render.
API does not return any files (ie. `?fields=*.*.*.*` returns no extra data)

## Other Context & Screenshots

![Screen Shot 2019-06-20 at 18 34 45](https://user-images.githubusercontent.com/1035590/59865892-835a1680-938a-11e9-9894-3266dd478d67.png)
![Screen Shot 2019-06-20 at 18 34 13](https://user-images.githubusercontent.com/1035590/59865893-835a1680-938a-11e9-8d8b-7c08e3986465.png)

## Technical Details

- Device: Macbook
- OS: macOS 10.13
- Web Server: Apache/2.4.39
- PHP Version:  PHP 7.1
- Database: 15.1
- Install Method: wget && unzip

**Comment by benhaynes** [comment]
This has been fixed on `master` and should be released in the next 24h. :)

**Comment by gridsystem** [comment]
Was this merged into a release? I'm still getting the same on 7.6.0

**Comment by benhaynes** [comment]
It should have been in 7.6... and we also just released another. Could you pull the latest, update your database, clear cache, refresh, and see if the issue persists?
