### ISSUE TITLE
Broken alignment of text in M2O fields in 11.9.3

### ISSUE THREAD

**Issue by aritraroy** [directus/directus#25546]
### Describe the Bug

I have updated to version 11.9.3 and I am seeing that all the M2O fields have the text alignment broken. 

If you refer to the screenshot below the text is not vertically centered and thus is slightly cut off from the bottom. I have seen this issue in 11.9.0 also, so it might have been introduced there I guess.

![Image](https://github.com/user-attachments/assets/309e261c-a1bc-49e6-bf8e-8058e189c168)

### To Reproduce

1. Update to 11.9.3 and add any M2O field.
2. You will find the text in it not properly aligned an dis cut off from the bottom.

### Directus Version

11.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ComfortablyCoding** [comment]
Thanks for reporting this! It looks like this is a duplicate of #25448, I'll go ahead and close this one. If you believe this is a separate issue, feel free to leave a comment. #25448 has been fixed by #25477 which will be available with the next release.

**Comment by aritraroy** [comment]
Thank you. I have checked the latest release 11.10.0 and this issue is fixed now.

I had created another issue (https://github.com/directus/directus/issues/25547) which I assumed is related to this issue and will get fixed in this new release. But it still seems to be broken in 11.10.0. Can you kindly check it?

**Comment by ComfortablyCoding** [comment]
Although it may be related it does indeed look like it is still present. It will be addressed as a separate issue, any progress on it can be followed there.

**Comment by aritraroy** [comment]
Okay sure. I will follow this thread (https://github.com/directus/directus/issues/25547) for updates on this fix.

Actually, I wanted to update to the latest version but because of this issue I am still waiting on an older version.
