### ISSUE TITLE
Auth not working as expected in the SDK

### ISSUE THREAD

**Issue by BartCRMstrategen** [directus/directus#5207]
1) The issue and what you expected to happen
    Basicly what i want to do is sign in and get the current user but that does not work with the script under this.
    It gives me the following errors: 
![image](https://user-images.githubusercontent.com/77833517/115836986-67a57880-a418-11eb-8706-28e5c9e5c092.png)
    I also tried this using Cookie mode instead of JSON, but it gives the same result

2) Exact steps to reproduce this issue
    I have created a fresh db/install and i tried the following code (in vue)
    The version of the sdk is also 60
    Code: https://pastebin.com/iPbDTgaa
`

3) Your environment:
    What version of Directus you are using: RC60
    Which DBMS are you using: MySQL
    Which deployment are you using: npm start (directus start)
    What browser are you using: Chrome

**Comment by WoLfulus** [comment]
Fixed on https://github.com/directus/directus/commit/48fbb6f255bc533f0679c5762144d8e5ba5104f9

Sorry about that!

**Comment by BartCRMstrategen** [comment]
The issue still remains, basicly the auth token is missing in the headers.

**Comment by WoLfulus** [comment]
Keeping it open until next release

**Comment by rijkvanzanten** [comment]
This is fixed and will be released in v9.0.0-rc.61
