### ISSUE TITLE
Ordering collection navigation open the choice

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#5872]
Small bug that can be disturbing when you have many collections.

When ordering the collection list in the navigation option of the role page, when I release the mouse in the title of the option it opens the option.
For example : I want to inverse _cms_actualite_ and _cms_evenement_. When I release on the icon at the left, no problem. But when I release _cms_actualite_ on the title _cms_evenement_, it opens the modal for _cms_evenement_ :

https://user-images.githubusercontent.com/6079305/119509313-d2780580-bd70-11eb-8dbb-91dc5a29d69f.mov

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/pull/6056

**Comment by pierre-H** [comment]
The problem is still effective event with the RC 73 :

https://user-images.githubusercontent.com/6079305/120781904-c981f380-c529-11eb-9769-bc6dd00f7ebc.mov
