### ISSUE TITLE
Automatic disconnection, with Error "Route /auth/refresh doesn't exist"

### ISSUE THREAD

**Issue by 3615alexis** [directus/directus#6227]
Hello,

Not connected, on the loging page, I have the following error in my browser console :

![image](https://user-images.githubusercontent.com/6710698/121777534-f6ba4b80-cb92-11eb-81ea-596aff375ba5.png)

Then, I can connect anyway. Once connected, I can navigate anywhere.
But if I go to the page "/admin/docs/getting-started/introduction/", and then try to go back to another page, I'm disconnected whith no reason.

When I login again, I'm "stuck" on page "/admin/docs/getting-started/introduction/" (as it is the "last_page" logged in the directus_users table), and again if I try to go on another page, I'm disconnected.

When I take a look at the error above by clicking on ":8055/auth/refresh:1" in my console, this is the message I have : 

{"errors":[{"message":"Route /auth/refresh doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}

The error is occurring whatever is my web browser (Chrome, Firefox, Edge), device (laptop, smartphone), etc.

Thanks in advance for your help !

Alexis

---

### Project details
Directus Version: 9.0.0-rc.75
Environment: false
OS: Linux 5.10.17-v7l+
Node: 14.17.0

**Comment by dnndev** [comment]
I can confirm this as well. Additionally, if you reload a page (for instance /admin/collections/documents ) then you are logged out.

**Comment by rijkvanzanten** [comment]
I'm having some trouble reproducing this. Are you using any webserver as proxy in front of Directus? Could it be that headers/cookies are stripped out?

**Comment by dnndev** [comment]
Yes. I’m using NGINX as a reverse proxy. I’ll have to investigate headers/cookies, however, I did not experience this in RC73, the previous version I’d installed.

**Comment by 3615alexis** [comment]
On my side I don't have a proxy installed, I'm just making some tests on a Raspberry Pi (OS Raspbian Buster).
I've installed Node 14.17.0 with npm 7.17.0 on it. Then I installed Directus following the official documentation. Then I accessed my app on localhost:8055 and that's all.

**Comment by 3615alexis** [comment]
Hello again,

I forgot to mention my Directus installation is done on another port than 8055.
I made some more tests and indeed : 
- when I install a new Directus on port 8055, it works correctly
- but if I install Directus on another port, I get the issue

Do you think it could be related to what's explained in the documentation : 
![image](https://user-images.githubusercontent.com/6710698/122235018-a35f3a80-cebd-11eb-81ed-5ded2a4aeba7.png)
What should be done exactly ? 

I don't know if @dnndev has the same situation (using another port) ?

Thanks,

Alexis

**Comment by rijkvanzanten** [comment]
@3615alexis Odd! AFAIK, Directus doesn't do anything with the port in regards to the refresh cookie 🤔 

Could you confirm the values for the `PUBLIC_URL` and `REFRESH_TOKEN_COOKIE_DOMAIN` environment variables? They should both be the full domain of where your API is accessible

**Comment by dnndev** [comment]
For my setup, I am running a separate Directus 9 instance (not yet upgraded) on a different port but the site in question is running on port 8055. `PUBLIC_URL="/"`. I do not have a `REFRESH_TOKEN_COOKIE_DOMAIN` environment variable set.

**Comment by 3615alexis** [comment]
Same for me, I do have : 

- PUBLIC_URL="/"
- not any REFRESH_TOKEN_COOKIE_DOMAIN variable

**Comment by rijkvanzanten** [comment]
I think @3615alexis was on the right track with saying this might be a configuration issue which causes the cookie not to be set.

Are these on "live" domains w/ HTTPS? I believe some browsers (chrome et al.) recently started requiring cookies to be set to "secure" when that's the case 🤔 

Regardless of that, the 404 for the endpoint itself doesn't make sense to me. @3615alexis could you confirm that's still the case, or is it just the 400 / 401 for not authorized?

**Comment by 3615alexis** [comment]
I just made a few more tests : 
- I switched the "working" install (install A) from port 8055 to port 8054
- and I switched the "not working" install (install B) from other port to port 8055 
=> in the end, install A is still the only one working, even on this other port 

BUT I just found out something : 
- install B not working was RC75 
- and Install A (installed today) is RC76 : 
![image](https://user-images.githubusercontent.com/6710698/122258025-e2e35200-ced0-11eb-9eaf-64e1f6f6ee82.png)

So it seems the arrival of RC76 fixed the issue ! No idea why, but I'll try upgrading my previous install with this one

**Comment by dnndev** [comment]
I've just updated to RC76 as well and the problem appears to have resolved itself. I had made no other changes.

**Comment by 3615alexis** [comment]
I confirm : I just upgraded "install B" to RC76, and the problem is not occurring anymore.

However I still have the same message in the console :

![image](https://user-images.githubusercontent.com/6710698/122259122-196d9c80-ced2-11eb-94a9-975860160a33.png)
 
So it seems the problem was not coming from there in the end. 

Do you have an idea about the changes between RC75 and RC76 that could explain the issue we had ?

**Comment by rijkvanzanten** [comment]
Ahhhhh yes that makes total sense now!

There was an issue with the literal string value "false" in 75 that was resolved (https://github.com/directus/directus/issues/6189), which would trigger secure to be enabled in this case, which causes issues in the cookie!

> However I still have the same message in the console :

This is expected and normal operations. Unfortunately, browsers don't let us treat 4xx http requests as successful. (The app doesn't know whether or not it has a refresh cookie available, so it tries refreshing every time. If the cookie doesn't exist, the API responds with a 401 (expected), which makes that message show up in the browser 👍🏻

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/directus/issues/6189

**Comment by donavan-tangible** [comment]
I'm still have this issue with Directus 10.3.0

{"errors":[{"message":"Route /auth/refresh doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}

**Comment by rijkvanzanten** [comment]
> I'm still have this issue with Directus 10.3.0
> 
> {"errors":[{"message":"Route /auth/refresh doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}

This closed issue is over 2 years old, and was traced back to a root cause that was resolved. You're most likely running into a different issue with the same symptoms 👍🏻 Mind opening a new issue? Ty!
