### ISSUE TITLE
DateTime Interface "now" doesn't align with database NOW()

### ISSUE THREAD

**Issue by mrjoops** [directus/directus#6857]
### Describe the Bug

Background:
* I live under the UTC+2 timezone
* My server is UTC
* I use the official Directus Docker image with embedded SQLite database with no custom settings

Description:
Since server time and user time may differ (worldwide web, you know 😉), I expect Directus to be able to handle correctly timezone stuff.
Actually, it's not the case, the timezone is completely ignored, leading to some weird issues: a single event can be associated to two different times, the server one and the user one (see how to reproduce the bug).

At first, I suspected a display-only issue but after further examination, it's not the case 😕.

You can usually deal with this issue by storing the timezone data along with the datetime (1), or by ensuring all the datetimes are stored in UTC (2).
Since Directus use timestamps to store datetimes (at least with SQLite), you may choose the second solution.

I would gladly have helped with this at the time of Directus 8 since I'm more a PHP person, so you got all my sympathy for this 🙂, and keep up the good work, Directus is awesome!

### To Reproduce

1. Create a new collection with the "Created On" optional system field
2. Click "Show Field on Detail" on the `date_created` field
3. Edit the `date_created` field: under the "Display" panel, uncheck the "Relative" checkbox and set the "Format" to something more developer-friendly like `yyyy-MM-dd'T'HH:mm:ssXX`
4. Add a standard field to the collection, set its type to DateTime and under the "Display" panel set the "Format" to  `yyyy-MM-dd'T'HH:mm:ssXX` too
5. Create an item in the collection and sets the date to "Now" in the datepicker
6. Abracadabra! Now you see the two dates are different (provided you're not in the same timezone as the server).

For me it's `2021-07-16T12:35:37+0200` and `2021-07-16T14:35:35+0200`. The second one is correct but I suspect someone from another timezone won't agree.

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

16.4.1

### What database are you using?

SQLite 3.34.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> Actually, it's not the case, the timezone is completely ignored

This is not entirely true. Directus relies on the difference in timestamp (w/ timezone info) vs datetime (without) for the timezone abstraction. Timestamp values are saved and retrieved with the timezone info (the `+0200` at the end), while datetime fields are saved/retrieved as is (timezone ignored). 

What you're describing here is the difference between what the API saves automatically (created_on), and what the app pre-fills when you click "Set to now". One is done in Node, the other in the browser. 

Seeing your server is in "UTC", I would've expected this to save two different values, though not the values you shared. It should've saved `2021-07-16T12:35:37Z` and `2021-07-16T14:35:35+0200`.

**Comment by mrjoops** [comment]
I see you changed the title: it sure needed to be changed but I don't agree with the new one. Why? Let's cite myself 😲:

> I suspect someone from another timezone won't agree.

I actually did the test and change my local timezone, now I'm in Islamabad (UTC+5) and here's what I see:
`2021-07-16T12:35:37+0500` and `2021-07-16T14:35:35+0500`.

This seems to prove that the issue is not only related to the difference between the app and the API.

**Comment by rijkvanzanten** [comment]
I'm not following..

> I actually did the test and change my local timezone

Changed local timezone _where_? Where is your Docker container running in the first place? Are you sure the server time in the Docker container is UTC? 

What I stated earlier should still apply afaict. The server-generated one should've saved with UTC, as the server time is supposedly UTC. The timestamp generated in the app should be saved with the local timezone information, as it's a timestamp field. So with your +5 example, we'd still expect `2021-07-16T12:35:37Z` and `2021-07-16T17:35:35+0500` for server and browser respectively

**Comment by mrjoops** [comment]
I changed my local timezone client-side, to emulate a different user in another place in the world. The server is untouched.

I did not create a new entry with this new timezone, I just looked at the previously entered data.

Sure, the saved timestamp did not change in database. The frontend just seem to add the current timezone to the TZ-less datetime it gets from the API.

By the way, as an end-user, I expect to see the dates converted to my local timezone, not to convert them by myself.

**Comment by rijkvanzanten** [comment]
I believe this is fixed by https://github.com/directus/directus/pull/7200

**Comment by mrjoops** [comment]
Hi @rijkvanzanten, I just tested with Directus 9.0.0-rc.90 and the issue still exists

**Comment by rijkvanzanten** [comment]
On second read, I believe this is how it's supposed to work. The `datetime` type saves the value as provided as-is, so if the user in the app provides it from their local timezone as `2021-08-16T17:31:12`, that's what's being stored. When the server generates the datetime, that datetime will also be saved as is, which is `2021-08-16T15:31:12`. The `datetime` type doesn't do any timezone conversions.

**Comment by mrjoops** [comment]
Hi @rijkvanzanten,
I think I understand quite well how it works, you mentioned it earlier: Directus don't store the timezone and all dates are saved as is, this is precisely the issue I will elaborate right now.

This behavior is acceptable if you use only server-generated timestamp (system fields in Directus) because you can know the timezone of the server. Note that this behavior doesn't work anymore if the sysadmin change the timezone of the server, because he moved it from Dublin to New York for example (yes, some sysadmins prefer to match the TZ with the location of the server): all the timestamps become instantly false.

Now if you add to your model a client-generated timestamp (user input), things get worse: imagine you created a ToDo collection, with some fields like task, assignee, due_date.
Let's say John, who lives in Apia, on a charming island (UTC+13, https://www.timeanddate.com/worldclock/samoa/apia), creates the following entry in Directus:
* task: Bring the turkey for Christmas eve!
* assignee: Jane
* due_date: 2021-12-24 18:00:00

Jane lives in Alofi, on an island not far from John (611 km, UTC-11, https://www.timeanddate.com/worldclock/niue/alofi).
The problem is that if Jane believes what is displayed in Directus, she will be 24 hours late to the party!

I finally hope that this example will persuade the Directus team to take timezone subject into account.

**Comment by rijkvanzanten** [comment]
Yeah that all makes sense, and that's what we consider the different between datetime and timestamps. Datetime are values that are stored and retrieved as-is, without any timezone conversion whatsoever. Timestamp fields are converted to/from UTC .

**Comment by mrjoops** [comment]
I didn't find any difference between datetime and timestamp in Directus. They display and store the same. In fact when I click edit on a timestamp field, "DateTime" appears as the type.

**Comment by rijkvanzanten** [comment]
> In fact when I click edit on a timestamp field, "DateTime" appears as the type.

That sounds like a bug to me. Mind opening a new issue for that?
